### ISSUE TITLE
An error occured

### ISSUE THREAD

**Issue by netkimjh** [jdjaxon/linux_cac#1]
I followed the instruction and see the following error in Chrome and Firefox.
```
An error occurred
No valid client certificate found in the request. No valid certificates found in the user's certificate store.
Please try again after closing and reopening the browser and choose a different authentication method.
```
The weird thing is that I can see the all certificates in the setting of both Chrome and Firefox.

**Comment by jdjaxon** [comment]
Did you do the automated or manual configuration?

**Comment by netkimjh** [comment]
Mine is
```
 Reader 0: Broadcom Corp 58200 [Contacted SmartCard] (0123456789ABCD) 00 00
  Event number: 0
  Card state: Card inserted, 
  ```
  I cannot see any `Shared Mode`. Is it the problem?

**Comment by netkimjh** [comment]
On the web page: dod.teams.microsoft.us
I clicked `Sign in with CAC/PIV`, and nothing popped up.
Usually, the new window for selecting CA50 something appears.

**Comment by jdjaxon** [comment]
What OS and version are you using?

Did you do the automated installation?

**Comment by netkimjh** [comment]
It is Ubuntu 20.04
and I ran
`wget | sudo sh -c "$(wget https://raw.githubusercontent.com/jdjaxon/linux_cac/main/cac_setup.sh -O -)"
-- | --`
Also, I did
```
Download DOD certs from DISA [here](https://militarycac.com/maccerts/AllCerts.zip).
Unzip the AllCerts.zip folder using the following command:

unzip AllCerts.zip -d AllCerts
```
and followed `https://github.com/jdjaxon/linux_cac#google-chrome`

**Comment by jdjaxon** [comment]
After running the `wget` command, everything should would have ran automatically. You didn't need to do any steps from the manual configuration. I think running both may have caused an issue. Did you have any errors when running the script?

I have some troubleshooting steps that may remedy the situation:

1. Start in you home directory
2. Navigate to `.pki/nssdb`
3. Open the pkcs11.txt and make sure it has the following lines:
``` 
library=/usr/lib64/libcackey.so
name=CAC Module
```

The certificates should still be installed.

**Comment by netkimjh** [comment]
I found multiple line repeated in `pkcs11.txt`, so I deleted.

and the output of `find "$HOME" -name ".pki" 2>/dev/null ` is

`/home/<my computer name>/.pki`

**Comment by netkimjh** [comment]
With Chrome, I can see only the following error message when I hit the button `Sign in with CAC/PIV`

![image](https://user-images.githubusercontent.com/13003647/160037037-6cab5327-fdf7-40a0-b673-8db99234c21a.png)

**Comment by jdjaxon** [comment]
Run the following commands.

1. Determine the location of libcackey.so:
```
find / -name "libcackey.so" 2>/dev/null
```
2. Version of cackey:
```
apt-cache policy cackey
```
3. Contents of Chrome's `pkcs11.txt`:
```
cat $HOME/.pki/nssdb/pkcs11.txt
```
4. System version and architecture:
```
uname -a
```
Post the results here.

I'm going to do my best to get you running. I just need to see if everything is in the state it should be.

**Comment by jdjaxon** [comment]
Open chrome's pkcs11.txt file in your editor of choice (you may need to `sudo` this depending on permissions).

Change:
```
library=/usr/lib64/libcackey.so
name=CAC Module
```
To this:
```
library=/usr/lib/libcackey.so
name=CAC Module
```
This change is to make it match the results of the find you did for `libcackey.so`. This is an error in my script. I need to change the script to use the result of that find when it adds the library to your `pkcs11.txt` file. You'll likely need to do the same change in the mozilla `pkcs11.txt` file. Make sure to restart chrome after making this change. Let me know if that works.

**Comment by netkimjh** [comment]
Unfortunately, that change cause the broken chrome. Chrome is closing itself with `library=/usr/lib/libcackey.so`

**Comment by netkimjh** [comment]
Interestingly, once I changed it to `library=/usr/lib/libcackey.so` and turned back to `library=/usr/lib64/libcackey.so`, DOD CAC login is working now!
Thank you very much!

**Comment by jdjaxon** [comment]
Sorry that was such a battle. Glad I could help!
