### ISSUE TITLE
Chrome+Firefox not selecting cert after reboot

### ISSUE THREAD

**Issue by mdeyo** [jdjaxon/linux_cac#10]
Awesome project! Been struggling for years to get CAC access to work on my Ubuntu machines, and would just give up after a few hours each time. Used your Automated Installation script and then could easily login to CAC systems on both Firefox and Chrome.

But that was yesterday... After a reboot today neither browser will let me select a certificate from my CAC. Firefox will ask for the password then not select a cert, while Chrome will ask for the password 5 times before failing to select a cert. The 4 certificates on my CAC are still visible to both browsers in their respective Settings/Certs menus.

Similar to issue #5 but this did work yesterday and it's prompting for password, just no cert selection and fails to login to CAC-enabled websites. 

Similar it issue #7 but the pcscd.service and pcscd.socket are active on first attempt.

Running Ubuntu 20.04.5 LTS and using Chrome V105.0.5195.125 and Firefox V105.0. Tried the troubleshooting steps, like clearing data and history. All the outputs/debugging from previous issues seem nominal, which is why I'm struggling to figure this out based on previous/known issues. I feel like there's one small mistake that I'm missing.

Thanks for sharing your work on this!

**Comment by jdjaxon** [comment]
It was a step that I missed here but have since added on another branch that hasn'tbeen merged. Try running this:
```
sudo systemctl start pcscd
sudo systemctl enable pcscd
```
After that, make sure the CAC is inserted and restart the browsers. If not then, try a reboot. That daemon is sometimes finicky. If you keep having issues, return here and I'll try to help you figure out what's going on.

**Comment by mdeyo** [comment]
Thanks for the quick response! Unfortunately that didn't help though, even after reboot and running them again. Now both Chrome and Firefox are looping on the password prompt but never selecting any certificates from the CAC.

When in the browser Settings/Cert page, it asks me to login to the device and correctly shows all 4 certs. The middleware is not working properly while talking to the CAC-enabled websites. I've been trying on DTS, the AF portal, and https://webmail.apps.mil/ email client.

**Comment by jdjaxon** [comment]
Can you try clearing the history and cache 8n both browsers? Sounds crazy, but I have seen this fix it before.

**Comment by mdeyo** [comment]
Clearing history and cache in both browsers and restarting them didn't have any effect. Wish it was that easy.

I did have Coolkey installed before, but removed it once your solution with Cackey worked.

My output for `modutil -dbdir sql:.pki/nssdb/ -list` is the following:

`Listing of PKCS #11 Modules
-----------------------------------------------------------
  1. NSS Internal PKCS #11 Module
	   uri: pkcs11:library-manufacturer=Mozilla%20Foundation;library-description=NSS%20Internal%20Crypto%20Services;library-version=3.49
	 slots: 2 slots attached
	status: loaded

	 slot: NSS Internal Cryptographic Services
	token: NSS Generic Crypto Services
	  uri: pkcs11:token=NSS%20Generic%20Crypto%20Services;manufacturer=Mozilla%20Foundation;serial=0000000000000000;model=NSS%203

	 slot: NSS User Private Key and Certificate Services
	token: NSS Certificate DB
	  uri: pkcs11:token=NSS%20Certificate%20DB;manufacturer=Mozilla%20Foundation;serial=0000000000000000;model=NSS%203

  2. CAC Module
	library name: /usr/lib64/libcackey.so
	   uri: pkcs11:library-manufacturer=U.S.%20Government;library-description=CACKey;library-version=0.7
	 slots: 2 slots attached
	status: loaded

	 slot: CACKey Slot
	token: DEYO.MATTHEW.QUINN.1270634474
	  uri: pkcs11:token=DEYO.MATTHEW.QUINN.1270634474;manufacturer=U.S.%20Government;model=CAC%20Token

	 slot: CACKey Slot
	token: US Government Certificates
	  uri: pkcs11:token=US%20Government%20Certificates;manufacturer=U.S.%20Government;model=CAC%20Token
-----------------------------------------------------------
`
Is the CAC Module supposed to have 2 slots?

**Comment by jdjaxon** [comment]
Can you post the contents of your `pkcs11.txt` here? If you don't know where it is, just run:
```
find $HOME -name pkcs11.txt
```

**Comment by mdeyo** [comment]
Yes, I have both those locations. The files are the same other than configdir matching each location. The Chrome one is here: 
```
library=
name=NSS Internal PKCS #11 Module
parameters=configdir='sql:/home/mdeyo/.pki/nssdb' certPrefix='' keyPrefix='' secmod='secmod.db' flags=optimizeSpace updatedir='' updateCertPrefix='' updateKeyPrefix='' updateid='' updateTokenDescription='' 
NSS=Flags=internal,critical trustOrder=75 cipherOrder=100 slotParams=(1={slotFlags=[ECC,RSA,DSA,DH,RC2,RC4,DES,RANDOM,SHA1,MD5,MD2,SSL,TLS,AES,Camellia,SEED,SHA256,SHA512] askpw=any timeout=30})

library=/usr/lib64/libcackey.so
name=CAC Module

**Comment by jdjaxon** [comment]
Your `pkcs11.txt` file mirrors mine, which is what I was hoping for. Do you still have coolkey onboard? It shouldn't cause issues if it isn't called by the `pkcs11.txt` file, but I'm just trying to neutralize edge cases here. If so, can you do an `apt purge` on that?

Also, can you run the following command and post it here:
```
systemctl status pcscd
```
I want to verify that everything with the daemon seems fully operational.

**Comment by jdjaxon** [comment]
Was `pcscd.socket` green?

**Comment by mdeyo** [comment]
Oh yes, both circles are green. I guess a screenshot would have been better

**Comment by jdjaxon** [comment]
If you insert your CAC and run `pcsc_scan`, does it detect that your CAC is inserted? It should display something similar to this:
```
➜  ~ pcsc_scan
Using reader plug'n play mechanism
Scanning present readers...
0: Alcor Micro AU9560 00 00
 
Tue Oct 11 16:22:23 2022
 Reader 0: Alcor Micro AU9560 00 00
  Event number: 0
  Card state: Card inserted, Shared Mode, 
  ATR: 3B F9 18 00 00 00 53 43 45 37 20 03 00 20 46
  ...
```

**Comment by mdeyo** [comment]
Yes detected by `pcsc_scan`

```Using reader plug'n play mechanism
Scanning present readers...
0: ACS ACR 38U-CCID 00 00
 
Tue Oct 11 13:24:05 2022
 Reader 0: ACS ACR 38U-CCID 00 00
  Event number: 0
  Card state: Card inserted, Shared Mode, 
  ATR: 3B 7D 96 00 00 80 31 80 65 B0 75 49 17 0F 83 00 90 00
...
```

And both browsers are able to see all 4 certs: 


![Screenshot from 2022-10-11 13-26-12](https://user-images.githubusercontent.com/6753443/195191969-e9c17ca4-10dc-4243-87ba-f1f51201a0d8.png)

**Comment by jdjaxon** [comment]
I'm honestly not sure, boss. Everything seems to be functioning as expected.

Additionally, I have another branch that you could use, but I would use it in conjunction with a few other steps. You can either use the `main` branch from the readme or you could us the one that I will include in the steps below, which is `compatability-for-2204` and works fine on 20.04. It is just written better and includes a few things that I missed initially. That being said, `main` has worked right out of the gate for most people I have had run it on 20.04. These outliers must have something I'm missing.

Using the nuclear approach:
1. I would purge all middleware packages (coolkey, cackey, etc.)
2. Run `sudo apt autoremove` to eliminate any stragglers
3. Do a `sudo apt update` and `sudo apt upgrade`
4. Clear history and cache on both browsers
5. Close both browsers
6. Then rerun the script:
New one:
```
sudo bash -c "$(wget https://raw.githubusercontent.com/jdjaxon/linux_cac/compatability-for-2204/cac_setup.sh -O -)"
```
   --- OR ---
Main branch (the one you originally ran):
```
sudo bash -c "$(wget https://raw.githubusercontent.com/jdjaxon/linux_cac/main/cac_setup.sh -O -)"
```

The cert portion will take a bit longer, but this approach may be better than searching for something we missed.

**Comment by mwaddell** [comment]
I've been seeing the same thing.  After every reboot, I need to rerun the command:
`for cert in *.cer; do certutil -d sql:"$HOME/.pki/nssdb" -A -t TC -n "$cert" -i "$cert"; done`

before I start up Chrome then everything works as normal.  If I don't do that, then Chrome doesn't recognize my cac

**Comment by mdeyo** [comment]
I went full nuclear option: wiped the disk and reinstalled Ubuntu 20.04.5 LTS and then used your automated script. Still no success and all the same symptoms. Even bought a new smart card reader today, just in case that was the problem. The browser security page will accept my CAC pin and show me all 4 certificates are working, but any CAC-enabled login that I try does not work. It's just stuck in a loop of asking for my pin until it gives up and says there was an error. This is all made more frustrating by the fact that it worked in both browsers on Monday night.

**Comment by mdeyo** [comment]
Can confirm, my issue was a blocked CAC. Your project is still awesome!

Closing the issue here, but the thread is great debugging/troubleshooting that future users could reference.

Summary: If you can view CAC certs in the browser cert settings, but then CAC-enabled logins fail or repeat PIN entries, then check the browser network tools for a 401 Unauthorized error (CAC probably blocked). Needs to be fixed by a personnel/CAC office.

**Comment by jdjaxon** [comment]
Thank you! I'm glad you were able to figure it out! I hadn't seen that one yet, so it's good to know for future reference. I also appreciate your patience while working through this.
