### ISSUE TITLE
Tested OS's

### ISSUE THREAD

**Issue by Stab-Rabbit-coding** [jdjaxon/linux_cac#12]
I successfully tested your scripts on Parrot OS 6.0.0-2 on both Firefox and Brave and it works.  You can update the Readme docs to indicate that Parrot OS is included in verified working distros.

**Comment by jdjaxon** [comment]
> I successfully tested your scripts on Parrot OS 6.0.0-2 on both Firefox and Brave and it works. You can update the Readme docs to indicate that Parrot OS is included in verified working distros.

I will close this issue once i update the readme. Thanks for your help!
