### ISSUE TITLE
Edge

### ISSUE THREAD

**Issue by muddro1** [jdjaxon/linux_cac#19]
Is there any chance to get this to work with Edge as well?

**Comment by pdzaffina** [comment]
@muddro1 I was able to get this to work on Edge on Kubuntu 22.04. I was able to logon to the Evaluations site. This is currently an issue (#20 ) with multiple browsers when trying to login to A365 (MS Office). Could you maybe send some information about your system?

**Comment by jdjaxon** [comment]
@muddro1, if you still need help with this issue, reopen this issue and follow up with @pdzaffina.
