### ISSUE TITLE
ESR compatibility

### ISSUE THREAD

**Issue by Corbachini33** [jdjaxon/linux_cac#28]
The script did not work with  Firefox ESR v128 on Ubuntu 24.04. Would it be possible to modify the script to that it could use firefox esr instead of regular firefox?

**Comment by jdjaxon** [comment]
> The script did not work with Firefox ESR v128 on Ubuntu 24.04. Would it be possible to modify the script to that it could use firefox esr instead of regular firefox?

I'll look into finding a way to incorporate this. While this is just an assumption, Firefox ESR likely has different config files and/or a different certificate database location that the script currently doesn't search for.

**Comment by jdjaxon** [comment]
I mentioned this in MR #26 where Firefox ESR was demonstrated to work on Debian 12.5. I have also transitioned to using OpenSC instead of CACKey, so I am going to close this issue. Please try rerunning the script. If it still does not work, feel free to reopen this issue.
