### ISSUE TITLE
Firefox authentication stopped working, Chrome loops PIN request

### ISSUE THREAD

**Issue by kram12085** [jdjaxon/linux_cac#4]
This issue may not be directly related to your script but you may have some insight.

Running Linux Mint 20.2. I had set up CAC for Firefox using militarycac.com and was working great. For seemingly no reason, it stopped working and will just pop up the attached image, never asking for PIN. I ran your script and the error still occurs.

Chrome will ask for my PIN twice, pause for about a minute, ask for my PIN twice, rinse and repeat. `pcsc_scan` detects my card and it works fine with the same reader in Windows. I've also tried all combinations of having the card inserted before starting Firefox, removing and reinserting, etc. Any idea what went wrong?

![Screenshot from 2022-05-05 18-25-06](https://user-images.githubusercontent.com/1285519/167052220-f11238cb-f778-4a6f-9e96-7cad453f7466.png)

**Comment by jdjaxon** [comment]
Which middleware are you using (OpenSC, cackey, CoolKey, etc.)? I'm most familiar with cackey.

**Comment by kram12085** [comment]
I had been using OpenSC. I realized your script also installed CACKey so I unloaded OpenSC and now it works fine! Still puzzled at why it stopped working but at least it's good now. Thanks for responding!

**Comment by jdjaxon** [comment]
Awesome! I'm glad you were able to get it resolved! Thanks for the insight into Mint as well.

As a side note, none of the CAC middleware libraries seem to work well together.
