### ISSUE TITLE
Can't upgrade cackey

### ISSUE THREAD

**Issue by bengooch7** [jdjaxon/linux_cac#6]
Currently a hold is placed on the cackey package so that it isn't upgraded past version 0.7.5-1. Upgrading cackey breaks the functionality of this automation script. 

Issues with this:
- Annoying warning from apt reminding you that a package is being held back
- Users can't upgrade their OS with packages held back and would need to either upgrade the package manually or remove it in order to upgrade OS versions. This breaks the functionality of CAC support across browsers.

**NOTE:** this can be fixed by removing cackey and rerunning this script, whch will reinstall the currently supported version and place the cackey package on hold again.

This method was the fastest way to provide a consistent solution. In the future, this will be remedied.

**Comment by jdjaxon** [comment]
In all the testing that Ben mentioned, the browser either wouldn't identify the CAC middleware or it would cause the browser to freeze/crash. As mentioned, fixing this is on our todo list, but our primary focus is creating a stable script that accomodates both Firefox and Chrome. The fixes for Firefox on 22.04 will be merged soon, and we will then shift our focus to this issue.

**Comment by bengooch7** [comment]
That does appear to be the case, yes.

Ben Gooch - Sent from my Pixel 6 Pro

**Comment by rquarry** [comment]
> or it would cause the browser to freeze/crash
I believe you'll find that the Firefox crashing with versions > 7.5 issue is that the library isn't compiled with zlib support. Use `ldd libcackey.so` to check whether zlib support is included. Compiling from source with zlib-dev files fixes this issue. I'm currently running the library out of /lib64 with no issues.

**Comment by jdjaxon** [comment]
> > or it would cause the browser to freeze/crash
> 
> I believe you'll find that the Firefox crashing with versions > 7.5 issue is that the library isn't compiled with zlib support. Use `ldd libcackey.so` to check whether zlib support is included. Compiling from source with zlib-dev files fixes this issue. I'm currently running the library out of /lib64 with no issues.

Thank you! I'll look into a way to integrate this once I have time.

**Comment by jdjaxon** [comment]
This project has moved to using OpenSC instead of CACKey, so I am closing this issue.
