### ISSUE TITLE
Stops working after reboot because pcsc daemon is disabled

### ISSUE THREAD

**Issue by pablobacho** [jdjaxon/linux_cac#7]
Hello,

The script works great right out of the box. However, after a reboot it stopped working on my computer. Turns out the pcsc daemon was not enabled and did not start automatically on boot.

This happened on Xubuntu 22.04 with Chrome. I just double-checked in a clean VM and got the same behavior.

After install, I'd add a call to ```systemctl enable pcscd```

Thanks for sharing your work!

**Comment by jdjaxon** [comment]
Thank you for the feedback!

We found this in troubleshooting as well. We have added this call to `systemctl` in another branch that has not yet been merged with main.

This branch will also correct issues with Firefox on the newest version (22.04) Ubuntu-based distros.

I will close this issue once we have the corrections merged.

Again, thank you!
