### ISSUE TITLE
Works for Brave Browser

### ISSUE THREAD

**Issue by kperont** [jdjaxon/linux_cac#8]
Hello,

This is not an "issue," but I thought I would let you know that this currently (at least appears to) work on the Brave Browser on Ubuntu 22.04 LTS. I just got this set up today, 17 June 2022, and everything seems to work as long as you turn Brave's shields off when logging into anything using a CAC login.

**Comment by jdjaxon** [comment]
Awesome! Thank you for the heads-up! We haven't had the chance to check many other browsers. I'm glad it worked for you though.
